package cz.muni.fi.pa165.travelagency.data.dao;

import cz.muni.fi.pa165.travelagency.data.entity.Customer;
import java.util.List;

/**
 * Represents DAO class for Customer class objects stored in database
 * @author David Simansky
 */
public interface CustomerDAO {
    
    /**
     * Creates new customer in database. Id is autogenerated by DB.
     * @param customer to be created
     * @throws IllegalArgumentException when customer is null or has alredy assigned id
     */
    public void create(Customer customer);
    
    /**
     * Retrieves customer with given ID from database
     * @param id of customer to be retrieved
     * @return customer with given id or null if doesn't exist
     * @throws IllegalArgumentException when id is null
     */
    public Customer get(Long id);
    
    /**
     * Updates existing customer in database
     * @param customer updated entry to be stored into database
     * @throws IllegalArgumentException if customer is null, has null id or doen't exist
     */
    public void update(Customer customer);
    
    /**
     * Deletes customer from database
     * @param customer to be removed
     * @throws IllegalArgumentException if customer is null, has null id or doen't exist
     */
    public void delete(Customer customer);
    
    /**
     * Retrieves all customer entries stored in database
     * @return list all customers from database
     */
    public List<Customer> getAll();
   
    


}
